import type { I18n, Lang } from './types';

export const PALETTE = [
	'#2BB673',
	'#3B6CF6',
	'#E8478B',
	'#9B5CE6',
	'#13A8C9',
	'#E5564B',
	'#C77D14',
	'#5B8C2A'
];

export const LANGS: Array<{ code: Lang; label: string }> = [
	{ code: 'en', label: 'English' },
	{ code: 'es', label: 'Espanol' },
	{ code: 'pt', label: 'Portugues' },
	{ code: 'fr', label: 'Francais' }
];

export const CURRENCIES = ['EUR', 'USD', 'GBP'] as const;

export const CURRENCY_SYMBOL: Record<(typeof CURRENCIES)[number], string> = {
	EUR: 'EUR ',
	USD: 'USD ',
	GBP: 'GBP '
};

export const STR: Record<Lang, I18n> = {
	en: {
		subtitle: 'Who ate what? Sorted in 60 seconds.',
		step1: 'STEP 1',
		step2: 'STEP 2',
		step3: 'STEP 3',
		who: "Who's in?",
		what: "What'd we get?",
		whoPaid: 'Who paid?',
		whoPaidSub: 'Tap whoever fronted the bill.',
		addFriend: 'Add a friend',
		add: 'Add',
		itemPh: 'Item (for example Wine)',
		everyone: 'Everyone',
		tapWho: 'Tap who shared it',
		addToSplit: 'Add friends to split this',
		eachWord: 'each',
		person: 'person',
		people: 'people',
		addFriendsFirst: 'Add friends first',
		noItems: 'No items yet',
		hintNoPeople: 'Once your table is set, list what everyone ordered.',
		hintItems: 'Type a name and price, then hit plus.',
		tipService: 'TIP / SERVICE',
		none: 'none',
		sharedExtra: 'Shared extra',
		sharedExtraSub: 'Cover charge, water, split equally',
		billTotal: 'BILL TOTAL',
		tally: 'Clear it',
		addPeopleItems: 'Add people and items',
		tableReceipt: 'TABLE RECEIPT',
		subtotal: 'SUBTOTAL',
		tip: 'TIP',
		extra: 'SHARED EXTRA',
		total: 'TOTAL',
		copyText: 'Copy text',
		shareLink: 'Share receipt',
		copied: 'Copied',
		linkCopied: 'Done!',
		nothing: 'Nothing to ring up yet',
		settleNoPeople: 'Add your friends and a few items, then come back.',
		settleItems: 'Add some items and tap who shared each one.',
		settings: 'Settings',
		language: 'LANGUAGE',
		currency: 'CURRENCY',
		done: 'Done',
		owe: 'you owe',
		billHead: 'Clear The Tab - bill split',
		itemsHead: 'Items',
		totalWord: 'Total',
		tipWord: 'Tip',
		extraWord: 'Shared extra',
		payerEmptyPeople: 'Add friends first, then mark who paid.',
		paysWhom: 'WHO PAYS WHOM',
		payVerb: 'pay',
		allSettled: 'All square - nobody owes a thing.',
		pickPaidHint: 'Set who paid above to get transfers.',
		paidBy: 'PAID BY',
		resetTab: 'Reset tab',
		installApp: 'Add to home screen'
	},
	es: {
		subtitle: 'Quien pidio que? Resuelto en 60 segundos.',
		step1: 'PASO 1',
		step2: 'PASO 2',
		step3: 'PASO 3',
		who: 'Quienes estan?',
		what: 'Que pedimos?',
		whoPaid: 'Quien pago?',
		whoPaidSub: 'Toca quien adelanto la cuenta.',
		addFriend: 'Anade a alguien',
		add: 'Anadir',
		itemPh: 'Plato (ejemplo Vino)',
		everyone: 'Todos',
		tapWho: 'Toca quien lo compartio',
		addToSplit: 'Anade amigos para dividir',
		eachWord: 'cada',
		person: 'persona',
		people: 'personas',
		addFriendsFirst: 'Anade amigos primero',
		noItems: 'Aun no hay platos',
		hintNoPeople: 'Cuando este la mesa, anota lo que pidio cada uno.',
		hintItems: 'Escribe nombre y precio, y pulsa mas.',
		tipService: 'PROPINA / SERVICIO',
		none: 'nada',
		sharedExtra: 'Extra compartido',
		sharedExtraSub: 'Cubierto, agua, a partes iguales',
		billTotal: 'TOTAL',
		tally: 'Calcular',
		addPeopleItems: 'Anade gente y platos',
		tableReceipt: 'RECIBO DE MESA',
		subtotal: 'SUBTOTAL',
		tip: 'PROPINA',
		extra: 'EXTRA',
		total: 'TOTAL',
		copyText: 'Copiar texto',
		shareLink: 'Compartir recibo',
		copied: 'Copiado',
		linkCopied: 'Listo!',
		nothing: 'Nada que cobrar todavia',
		settleNoPeople: 'Anade amigos y platos, luego vuelve a calcular.',
		settleItems: 'Anade platos y toca quien compartio cada uno.',
		settings: 'Ajustes',
		language: 'IDIOMA',
		currency: 'MONEDA',
		done: 'Listo',
		owe: 'debes',
		billHead: 'Clear The Tab - cuenta dividida',
		itemsHead: 'Platos',
		totalWord: 'Total',
		tipWord: 'Propina',
		extraWord: 'Extra compartido',
		payerEmptyPeople: 'Anade amigos y marca quien pago.',
		paysWhom: 'QUIEN PAGA A QUIEN',
		payVerb: 'paga a',
		allSettled: 'Todo en paz, nadie debe nada.',
		pickPaidHint: 'Marca quien pago para ver transferencias.',
		paidBy: 'PAGO',
		resetTab: 'Reiniciar cuenta',
		installApp: 'Anadir a inicio'
	},
	pt: {
		subtitle: 'Quem comeu o que? Resolvido em 60 segundos.',
		step1: 'PASSO 1',
		step2: 'PASSO 2',
		step3: 'PASSO 3',
		who: 'Quem esta?',
		what: 'O que pedimos?',
		whoPaid: 'Quem pagou?',
		whoPaidSub: 'Toca em quem adiantou a conta.',
		addFriend: 'Adiciona alguem',
		add: 'Adicionar',
		itemPh: 'Item (exemplo Vinho)',
		everyone: 'Todos',
		tapWho: 'Toca em quem dividiu',
		addToSplit: 'Adiciona amigos para dividir',
		eachWord: 'cada',
		person: 'pessoa',
		people: 'pessoas',
		addFriendsFirst: 'Adiciona amigos primeiro',
		noItems: 'Ainda sem itens',
		hintNoPeople: 'Quando a mesa estiver pronta, lista os pedidos.',
		hintItems: 'Escreve nome e preco e carrega mais.',
		tipService: 'GORJETA / SERVICO',
		none: 'nada',
		sharedExtra: 'Extra partilhado',
		sharedExtraSub: 'Couvert, agua, dividido por igual',
		billTotal: 'TOTAL',
		tally: 'Fechar conta',
		addPeopleItems: 'Adiciona pessoas e itens',
		tableReceipt: 'TALAO DA MESA',
		subtotal: 'SUBTOTAL',
		tip: 'GORJETA',
		extra: 'EXTRA',
		total: 'TOTAL',
		copyText: 'Copiar texto',
		shareLink: 'Partilhar talao',
		copied: 'Copiado',
		linkCopied: 'Pronto!',
		nothing: 'Nada para fechar ainda',
		settleNoPeople: 'Adiciona amigos e itens e depois fecha a conta.',
		settleItems: 'Adiciona itens e toca em quem dividiu.',
		settings: 'Definicoes',
		language: 'IDIOMA',
		currency: 'MOEDA',
		done: 'Pronto',
		owe: 'deves',
		billHead: 'Clear The Tab - conta dividida',
		itemsHead: 'Itens',
		totalWord: 'Total',
		tipWord: 'Gorjeta',
		extraWord: 'Extra partilhado',
		payerEmptyPeople: 'Adiciona amigos e marca quem pagou.',
		paysWhom: 'QUEM PAGA A QUEM',
		payVerb: 'paga a',
		allSettled: 'Tudo certo, ninguem deve nada.',
		pickPaidHint: 'Marca quem pagou para ver transferencias.',
		paidBy: 'PAGOU',
		resetTab: 'Reiniciar conta',
		installApp: 'Adicionar ao ecra inicial'
	},
	fr: {
		subtitle: 'Qui a pris quoi? Regle en 60 secondes.',
		step1: 'ETAPE 1',
		step2: 'ETAPE 2',
		step3: 'ETAPE 3',
		who: 'Qui est la?',
		what: 'On a pris quoi?',
		whoPaid: 'Qui a paye?',
		whoPaidSub: 'Touche qui a avance laddition.',
		addFriend: 'Ajoute un ami',
		add: 'Ajouter',
		itemPh: 'Plat (exemple Vin)',
		everyone: 'Tout le monde',
		tapWho: 'Touche qui a partage',
		addToSplit: 'Ajoute des amis pour partager',
		eachWord: 'chacun',
		person: 'personne',
		people: 'personnes',
		addFriendsFirst: 'Ajoute des amis dabord',
		noItems: 'Aucun plat',
		hintNoPeople: 'Une fois la table prete, liste les commandes.',
		hintItems: 'Saisis un nom et un prix puis plus.',
		tipService: 'POURBOIRE / SERVICE',
		none: 'aucun',
		sharedExtra: 'Extra partage',
		sharedExtraSub: 'Couvert, eau, partage a parts egales',
		billTotal: 'TOTAL',
		tally: 'Les comptes',
		addPeopleItems: 'Ajoute gens et plats',
		tableReceipt: 'TICKET DE TABLE',
		subtotal: 'SOUS-TOTAL',
		tip: 'POURBOIRE',
		extra: 'EXTRA',
		total: 'TOTAL',
		copyText: 'Copier',
		shareLink: 'Partager le recu',
		copied: 'Copie',
		linkCopied: 'OK!',
		nothing: 'Rien a encaisser pour linstant',
		settleNoPeople: 'Ajoute des amis et des plats puis reviens.',
		settleItems: 'Ajoute des plats et touche qui partage.',
		settings: 'Reglages',
		language: 'LANGUE',
		currency: 'DEVISE',
		done: 'OK',
		owe: 'tu dois',
		billHead: 'Clear The Tab - addition partagee',
		itemsHead: 'Plats',
		totalWord: 'Total',
		tipWord: 'Pourboire',
		extraWord: 'Extra partage',
		payerEmptyPeople: 'Ajoute des amis et indique qui a paye.',
		paysWhom: 'QUI PAIE QUI',
		payVerb: 'paie',
		allSettled: 'Tout est regle, personne ne doit rien.',
		pickPaidHint: 'Indique qui a paye pour voir les transferts.',
		paidBy: 'PAYE PAR',
		resetTab: 'Reinitialiser',
		installApp: "Ajouter a l'accueil"
	}
};
